name: kemenag_go_internal_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+12

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_flavor: ^1.1.4
  carousel_slider: ^2.2.1
  cached_network_image: ^2.2.0+1
  intl: ^0.16.1
  date_format: ^1.0.9
  documents_picker: ^1.0.0
  http: ^0.12.2
  bloc: ^6.1.0
  flutter_bloc: ^6.0.5
  equatable: ^1.2.5
  json_annotation: ^3.1.0
  json_serializable: ^3.5.0
  shared_preferences: ^0.5.12+2
  shimmer: ^1.1.2
  indonesia: ^1.0.1
  flutter_html: ^1.2.0
  firebase_core: ^0.5.0
  firebase_messaging: ^7.0.3
  overlay_support: ^1.0.5
  get_it: ^5.0.3
  flutter_local_notifications: ^3.0.1+2
  file_picker: ^2.1.7
  flutter_downloader: ^1.5.2
  dio: ^3.0.10
  image_gallery_saver: ^1.6.6
  permission_handler: ^5.1.0+2
  path_provider: ^1.6.24
  file_utils: ^0.1.4
  oktoast: ^2.3.2
  geocoding: ^1.0.5
  geolocator: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  flutter_launcher_icons: ^0.8.1
  

flutter_icons:
  image_path: "assets/images/icon.png" 
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
